const removeNumbers = (string) => {
  const regex = /\d+/
  let goodString = string.replace(regex, '')

  // Don't know why the . is not being replaces when a user leaves the '.' generated by the
  // input field when the user types twice the space bar
  goodString = string.replace(/\./g, '')
  return goodString
}

export default removeNumbers
